apiVersion: v1
kind: Service
metadata:
  name: rickandmorty-service
  namespace: develop
spec:
  selector:
    app: rickandmorty
  ports:
    - protocol: TCP
      port: 80        # Puerto expuesto dentro del cluster
      TargetPort: 3000  # Puerto del contenedor
      NodePort: 30080
      protocol: TCP
  type: NodePort       # Opciones: ClusterIP (default), NodePort, LoadBalancer