name: CI/CD Rick and Morty

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: felipeyorick
          password: Kaka1234$

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./
          push: true
          tags: felipeyorick/frontend-react:${{ github.sha }}

      - name: Update manifests repo
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          sed -i "s|felipeyorick/frontend-react:.*|felipeyorick/frontend-react:${{ github.sha }}|" k8s/dev/deployment.yaml
          git add k8s/dev/deployment.yaml
          git commit -m "Update image to ${{ github.sha }}"
          git push